### ISSUE TITLE
Fit in app

### ISSUE THREAD

**Issue by eaedkazubi** [Kyei-frank/Streamlit-App-for-ML-Model-Project#1]
Never fit anything in your app... You must just 'transform'/'predict'/'predict_proba'

**Comment by Kyei-frank** [comment]
Okay Emma, thank you.
This was my first streamlit/ ML App so I was not very used to the process. I will rectify it now.

**Comment by eaedk** [comment]
nothing has changed until now in your code...

**Comment by eaedk** [comment]
and do not use a loop for the encoder, it can encoded multiple values at once

**Comment by Kyei-frank** [comment]
I decided to do the whole modeling again using pipeline. That is why It was delayed for a while.
The issue is resolved now with pipeline.predict
